### ISSUE TITLE
[ discussion ] Thoughts on bootstrapping

### ISSUE THREAD

**Issue by acaloiaro** [zenhack/tempest#19]
:wave: I'm obviously new here. I'm excited about what you're building.

I want to share some thoughts on bootstrapping development environments. 

There are a few stumbling blocks to bootstrapping that I think can largely be solved with updates to `README.md` and `env.sh.example`. 

There are a few things, that when combined, make for a slower bootstrapping process: users, configuration/defaults, and environment variables. 

**users**

My first thought on users is that the default u/g combination `sandstorm` / `sandstorm` creates an immediate stumbling block to bootstrapping. The fact that the `sandstorm` u/g must already exist is not documented in `README.md`. The easy fix here is to add user/group creation to the build or runtime documentation.

The less easy fix is to question whether the the runtime user/group should be a part of the build process at all (i.e. `./configure --user=... --group=...`). Doing so makes deployment more brittle in that every system on which `tempest` will be launched must know the user/group with which `tempest` was built. This is obviously not a major impediment, but it seems an unnecessary constraint. 

My recommendation would be to drop `--user` and `--group` from the build process and by default run the process as the executing user. Then, add `TEMPEST_USER` and `TEMPEST_GROUP` environment variables to override the default behavior. 

**configuration/defaults/environment variables**

There are some configuration defaults that make setup more difficult than necessary. 

1. The default base url `local.sandstorm.io`. In order for developers to access their local instance, they must create a host file entry for this hostname before accessing the service. Use `localhost` instead. Add a `BASE_URL=http://localhost` to `env.sh.example`
2. Most developers don't want to execute things as `root` unless they must. Having a sub-1024 default port (80) means users should set `HTTP_PORT` to something else. Add `HTTP_PORT=8000` (or whatever you want) to `env.sh.example`
3. I probably pulled the trigger a bit early on this PR, but currently, `SMTP_*` vars are not actually optional: https://github.com/zenhack/tempest/pull/18
4. Finally, mention `env.sh.example` in the README

**Comment by zenhack** [comment]
Hello! Glad you're excited.

Responses to some specific things:

users: these are only actually used directly by `make install` (I just pushed a patch that removes the runtime constants, since we don't use them and shouldn't). That said we do need to fiddle with ownership/permissions on some of the installed files, so we do need to know what user the service will run as.

config:

1. `local.sandstorm.io` actually resolves to `127.0.0.1`, so there's no need to create a hosts entry. I *think* most browsers will also send `*.localhost` to the same box, but other tools won't, so `local.sandstorm.io` is actually probably more robust, as long as the developer doesn't lose their network connection. I think at some point we considered changing this in Sandstorm since browsers had started doing that, but decided against it (maybe @ocdtrekkie remembers the conversation?)
2. Re: running things as root: tempest doesn't actually run as root; `make install` sets `CAP_NET_BIND_SERVICE` on the `tempest` executable, which lets it bind to low ports as a regular user. Of course, this means we need root at install time, but the `tempest-sandbox-launcher` binary needs setuid for privileged operations anyway, so dropping this wouldn't solve the issue. Sandstorm actually could run as non-root, but this mostly ended up meaning our CI used a different code path from what was in prod on most machines, which is not great. So far I haven't found a solution that feels better than the simplicity of just having one way to launch it shared between dev & prod.
3. Yeah, we should fix this; been on my mental TODO list, which should probably get written down somewhere as the project gets more attention...
4. Good call; this was just oversight on my part.

Thanks for the feedback!

**Comment by ocdtrekkie** [comment]
I know *.localhost behavior was browser-specific. We probably could test how it behaves today, but I'd have to dig up the specific things that were broken for *.localhost on which browsers.

**Comment by zenhack** [comment]
3 & 4 are both fixed now.

**Comment by zenhack** [comment]
I'm going to close this; I don't think there's anything actionable here now.
